[package]
name = "mem_to_graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.3"
pyo3 = "0.18.2"

[lib]
name = "mem_to_graph"
crate-type = ["cdylib"]
